### ISSUE TITLE
CSV Configurations

### ISSUE THREAD

**Issue by seanreward** [seanr89/DataCreator#1]
var csvConfig = new CsvConfiguration(CultureInfo.InvariantCulture) { HasHeaderRecord = true, Delimiter = "," };
            using (var csvWriter = new CsvWriter(streamWriter, csvConfig))
            {
                var dateFormatOptions = new TypeConverterOptions { Formats = new[] { "yyyy-MM-dd HH:mm:ssz" } };
                csvWriter.Context.TypeConverterOptionsCache.AddOptions<DateTime>(dateFormatOptions);
                csvWriter.WriteRecords(records);
                streamWriter.Flush();
            }
        }

**Comment by seanr89** [comment]
Fix updated and changes resolved
